In [2]:
import numpy as np

In [3]:
matrix_A = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(matrix_A)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


## (i)

In [4]:

matrix_A = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
transpose_x =np.transpose(matrix_A)
print(transpose_x)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


## (ii)

In [5]:
matrix_A = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
det_matrix_A = np.linalg.det(matrix_A)
print(det_matrix_A)

0.2299999999999999


## (iii)

In [19]:
matrix_A = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
T        = np.linalg.eig(matrix_A)
print(T)







EigResult(eigenvalues=array([2.04100779, 0.82188052, 0.13711169]), eigenvectors=array([[-0.43721717, -0.85359707, -0.28321933],
       [-0.59931898,  0.51133314, -0.61591816],
       [-0.67056536,  0.09955128,  0.73514055]]))


## (iv)

In [23]:
matrix_A = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
B        = (transpose_x)*(matrix_A)
print(B)

[[1.   0.04 0.25]
 [0.04 1.   0.64]
 [0.25 0.64 1.  ]]
